### PR TITLE
Refactor GameLoop to Game class

### LINKED ISSUE #30: Simplify GameLoop usage
# DEFINITION OF DONE

- [x] It should not necessary add `using GameLoop::GameLoop`
- [x] It should not necessary declare class definition of Game with inheritance of GameLoop
- [x] It should update all current examples with the new usage 
- [x] It should only need to define event, update and render*.
- [ ] ~~It should possible define start and stop too.~~ (wontfix)
- [x] It should refactor GameLoop definition with proper usage of private and public method: some of them are public without need.
- [x] It should rename `render` method to `draw`
# Questions

- We should rename render to draw? Why?

### PR DESCRIPTION
**Pull request by ryukinix**
Closes #30 

Make it simpler to use. Removed start/stop due some C++
restrictions. Previous start method used now it's a common function
that runs on main() before game starts.

Take a look on examples, they are now more simpler.

### CODE REVIEW

**Comment by ryukinix** [comment]
ping

Please, review it. @rafaelcn @wesleycsj

**Comment by ryukinix** [comment]
I plan to merge that pull request until friday.

cc: @rafaelcn @wesleycsj

**Comment by wesleycsj** [comment]
Don't pull until friday. Wait for our review.

**Comment by ryukinix** [comment]
No worry, I'll wait until friday.

**Comment by wesleycsj** [comment]
I can't guarantee a review before friday, please let this open for indeterminate time. This is a really important feature, and should have a special care.

**Comment by ryukinix** [comment]
Ok, I'll wait until the end of the year

**Review by wesleycsj — APPROVED** [review]

**Pull request merged**
